### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by JohannesOehm** [NUMde/compass-numapp-backend#32]
**Describe the bug**
Even comparably small (140 kb) encrypted cannot be submitted, transmission is capped after 1,72 kb and a 413 kb is returned

**To Reproduce**
1. Load the GECCO Questionnaire from the Implementation Guide into the backend
2. Open Data4Life WebApp
3. Enter data 
4. Try to submit Questionnaire
5. See in Browser console and server terminal the error message: "PayloadTooLargeError: request entity too large"

**Expected behavior**
The Questionnaire can be submitted

**Smartphone (please complete the following information):**
- Windows 10, Firefox

**Solution**
Adding lmiit to the bodyParsers in ExpressServer.ts seems to fix this issue, even though I'm not sure this is the optimal solution:
`this.app.use(bodyParser.json({ limit: '50mb' }));`
`this.app.use(bodyParser.urlencoded({ extended: true, limit: '50mb' }));`

![grafik](https://user-images.githubusercontent.com/16564576/129317313-a1c85901-eeed-418d-90c1-8184103f2a5e.png)

Selected request was successfull after adding the limit parameter to bodyParser.

**Comment by mbastian93** [comment]
Are you sure you're using the latest version? as of #24 the size limit should have been increased; also the bodyparser was replaced with the parser from express.

**Comment by JohannesOehm** [comment]
No, I didn't use the latest version 😬😅 With the current version, it works. Thank you!
