### ISSUE TITLE
first generate keys, than create .env

### ISSUE THREAD

**Issue by dagmarkrefting** [NUMde/compass-numapp-backend#48]
**Describe the problem with the Documentation**
you need to add the keys in the .env file, so these must be generated first

**[Optional] Suggest information, that might be helpful**
Swap the two paragraphs: "Generating RSA key pair" and "Create .env file"

**Comment by mbastian93** [comment]
For local development purposes, the public/private keys don't need to be inserted in the .env but can be saved as files as described [here](https://github.com/NUMde/compass-numapp-backend#generating-rsa-key-pair). It is also state there, that these keys _can_ be inserted into the .env-file.

Maybe the lines [18 and 19](https://github.com/NUMde/compass-numapp-backend/blob/2693d8ddb49414f5a45c556f93b83798397868e4/.env.sample#L18) (and maybe line [21](https://github.com/NUMde/compass-numapp-backend/blob/2693d8ddb49414f5a45c556f93b83798397868e4/.env.sample#L21) as well) could be marked as comments to clarify that there are changes necessary.
