### ISSUE TITLE
Wrong database port in DB documentation 

### ISSUE THREAD

**Issue by dagmarkrefting** [NUMde/compass-numapp-backend#49]
**Describe the problem with the Documentation**
In https://github.com/NUMde/compass-numapp-backend/tree/main/db
the prerequisites say: DB runs on default port (5432)
However, output (and default value in flyway.js) is documented as:
Database: jdbc:database://localhost:15432/compass (PostgreSQL 12.1)

**[Optional] Suggest information, that might be helpful**
change 15432 to 5432

**Comment by mbastian93** [comment]
The issue here is not, that the port is wrong per se but that it might not be clear that this setup guide is explicitly for the use of OpenShift. This means the local port '15432' is forwarded via the oc CLI to the port '5432' of the database running on an OpenShift cluster.
